### ISSUE TITLE
BK4819 Application Note

### ISSUE THREAD

**Issue by tywtyw2002** [ludwich66/Quansheng_UV-K5_Wiki#14]
I found the  BK4819 Application Note online, here is the original version. The bottom link with the google translated version.

[BK4819(V3) Application Note 20210428_Chinese.pdf](https://github.com/ludwich66/Quansheng_UV-K5_Wiki/files/12504882/BK4819.V3.Application.Note.20210428_Chinese.pdf)

https://prkele.prk.tky.fi/~ftg/files/datasheets/

**Comment by ludwich66** [comment]
I have added here too thanx

**Comment by ludwich66** [comment]
OK
