### ISSUE TITLE
Aligned board images

### ISSUE THREAD

**Issue by egzumer** [ludwich66/Quansheng_UV-K5_Wiki#15]
All images were transformed, they align perfectly with pcb_front_01.jpg.

[bok2-3](https://github.com/ludwich66/Quansheng_UV-K5_Wiki/assets/14902414/694149f4-5d74-4863-be69-8b87bcd26882)
[bok2-4](https://github.com/ludwich66/Quansheng_UV-K5_Wiki/assets/14902414/847bd5ee-dd03-411e-815e-0c2e3a84359a)
[bok2-5](https://github.com/ludwich66/Quansheng_UV-K5_Wiki/assets/14902414/f86b076b-177f-449d-b055-664dc964a08d)
[bok3](https://github.com/ludwich66/Quansheng_UV-K5_Wiki/assets/14902414/c732114e-2cb2-4447-b9cc-1c3ebaca9f54)
[bokv2-1](https://github.com/ludwich66/Quansheng_UV-K5_Wiki/assets/14902414/d34150c2-0e06-458c-a9f6-9534d65a50e0)
[pcb_back_02](https://github.com/ludwich66/Quansheng_UV-K5_Wiki/assets/14902414/009e4dbe-c3c8-44b0-9dc9-2e3c18d291bc)
[bok1](https://github.com/ludwich66/Quansheng_UV-K5_Wiki/assets/14902414/92604780-752a-489d-af58-4a9562b758c2)
[bok2](https://github.com/ludwich66/Quansheng_UV-K5_Wiki/assets/14902414/00ecdf6c-cadf-4dd3-a4eb-965532d6e9d7)
[pcb_back_01](https://github.com/ludwich66/Quansheng_UV-K5_Wiki/assets/14902414/c7ba06b2-ed58-48b1-9c22-a71c87fe6fc1)
[XRay_RU1_2023-09-13](https://github.com/ludwich66/Quansheng_UV-K5_Wiki/assets/14902414/15dac6e4-d752-4d4d-a180-9293934e1b77)
[XRay_RU3_2023-09-13](https://github.com/ludwich66/Quansheng_UV-K5_Wiki/assets/14902414/2546ea84-5d05-4eed-a918-1dfdbbc54dec)

**Comment by ludwich66** [comment]
Hello Egzumer,
Are the pictures the same as here?
https://github.com/ludwich66/Quansheng_UV-K5_Wiki/tree/main/hardware/X-Ray
I put these original X-Rays together when they came out. What was oriented differently in your pictures?

Good work!!
Ludwich

**Comment by egzumer** [comment]
Those are the same pictures but transformed. Open them up you'll see. Just open multiple of my images in separate browser cards and switch between them.
