### ISSUE TITLE
Add kamilsss655 to the list of custom firmwares.

### ISSUE THREAD

**Issue by hackbyte** [ludwich66/Quansheng_UV-K5_Wiki#22]
Heya, can you add https://github.com/kamilsss655/uv-k5-firmware-custom to the firmwares listed in https://github.com/ludwich66/Quansheng_UV-K5_Wiki/wiki/Modded-Firmwares please?

It's a fork of egzumers work.

Thx in advance,

hacky

**Comment by ludwich66** [comment]
My List of Custom Firmwares is not pretty organized.
There are so many Versions - i don't know which Version has advantages or...
Do you can describe what's the characteristic of this Fork?
... and its added ;-)
