### ISSUE TITLE
Kicad schematic and PCB components

### ISSUE THREAD

**Issue by iz2fly** [ludwich66/Quansheng_UV-K5_Wiki#23]
I can't find any correspondence in names and numbers between the Kicad schematic and the components labeled on the PCB.
How do I find a component on the PCB starting from the schematic?

**Comment by ludwich66** [comment]
Sorry for the late response.
There are different Formats.
1. PCB-Picture with Markings and a List of corresponding Parts
https://github.com/ludwich66/Quansheng_UV-K5_Wiki/wiki/Parts---Teile
2. Schematic-Part drawed from different Users (With own numbers) and new and redrawed (Kicad)Parts based on this Material.

Keep an eye on the hardware/circuit diagram Channes and be patient ;-)

**Comment by ludwich66** [comment]
Did you find it ?

**Comment by iz2fly** [comment]
> Did you find it ?

Ok, very complete scheme.
I still can't find a match between the values on the scheme and the PCB. So I don't know if they match.
Example:
PCB L4=16nH and 4.7u scheme
PCB L5= 16nH and 9n scheme
![Quansheng_01](https://github.com/ludwich66/Quansheng_UV-K5_Wiki/assets/56764775/4d1cc562-3e0d-4a3a-8ed3-5c6528d57d8f)

**Comment by ludwich66** [comment]
Sorry for the confusion.
There is an inc. a corrected component overview as a list and an interactive materials list (iBOM) that “fit together”. If we switch to 1.0 after the feedback on version 0.9, I will clean up the WIKI

<img width="285" alt="image" src="https://github.com/ludwich66/Quansheng_UV-K5_Wiki/assets/12202733/d11e9bff-02ad-4d74-9e85-0c387441153e">

https://github.com/mentalDetector/Quansheng_UV-K5_PCB_R51-V1.4_PCB_Reversing_Rev._0.9

https://github.com/ludwich66/Quansheng_UV-K5_Wiki/wiki/PCB_R1.4_BOM

https://htmlpreview.github.io/?https://github.com/ludwich66/Quansheng_UV-K5_Wiki/blob/main/hardware/ibom.html

ludwich
