### ISSUE TITLE
armel/uv-k5-firmware-custom

### ISSUE THREAD

**Issue by fcatt** [ludwich66/Quansheng_UV-K5_Wiki#31]
Please add https://github.com/armel/uv-k5-firmware-custom to the list.

This fork of egzumer/uv-k5-firmware-custom is very active and the author @armel has a Youtube channel to expose his work. The firmware is well documented in English and French.

The same author has a custom driver for CHIRP: https://github.com/armel/uv-k5-chirp-driver

**Comment by ludwich66** [comment]
Its done!
